[package]
name = "agc-rs"
version = "0.1.0"
edition = "2021"
authors = ["AGC Rust Wrapper Authors"]
description = "Rust bindings for AGC (Assembled Genomes Compressor)"
license = "MIT"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
cmake = "0.1"
